import Head from 'next/head'
import Expertise from './components/Expertise'
import Header from './components/Header'
import Hero from './components/Hero'
import MyWork from './components/MyWork'
import About from './components/About'
import Contact from './components/Contact'


export default function Home() {
  return (
    <>
      <Head>
        <title>Aaron Robinson Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
     
     <main>
      
      <section>
        <Hero />
      </section>

      <section>
        <About />
      </section>

     <section>
        <Expertise />
      </section>

      <section>
        <MyWork />
      </section>

      <section>
        <Contact />
      </section>
     
     </main>

    
    </>
  )
}
